### ISSUE TITLE
Grass not dropping seeds

### ISSUE THREAD

**Issue by osba666** [enemeez/simplefarming#68] opened 2020-03-07 01:14 UTC
**Forge Version**
1.15.2
**Mod list (optional)**

**Log file (optional)**

**Describe the issue**
the grass does not release any type of seed :(

**Comment by cech12** [comment] 2020-04-09 10:42
Do you have some other mods installed? My mod Ceramic Shears had the same issue in combination with other mods, that I fixed in my new release.

**Comment by caligator** [comment] 2020-05-05 09:05
I have this in my 1.0.0 version of my modpack exhibiting the same behavior. sometimes it works when I reset the game, but most of the time the drops are at 0, even when I toggle the wild seed drop in the config. im using the 1.2.7 beta of your mod for such. 

mod load list is found in the info of the pack; https://www.curseforge.com/minecraft/modpacks/oops-all-mods

**Comment by cech12** [comment] 2020-05-06 09:05
Maxbe it is caused by another mod. You can test it, when you temporarily deactivate Simple Farming an test which mod is changing the loot table of Grass.

**Comment by caligator** [comment] 2020-05-06 09:16
I have toggled the mod on and off and pinned it *specifically* to simple farming. I have tried swapping some of the other mods I have in my pack in further testing, and it still exhibits the same behaviors. Sent from Mail for Windows 10 From: cech12Sent: Wednesday, May 6, 2020 4:05 AMTo: enemeez/simplefarmingCc: caligator; CommentSubject: Re: [enemeez/simplefarming] Grass not dropping seeds (#68) Maybe it is caused by another mod. You can test it, when you temporarily deactivate Simple Farming an test which mod is changing the loot table of Grass.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by cech12** [comment] 2020-05-06 11:42
It is a bug of occultism mod. When you disable occultism all works well. I opened a PR at its repository to fix that issue.

**Comment by cech12** [comment] 2020-05-06 13:49
The fix was merged and should be included in the next update of occultism.

**Closed** 2020-05-23 07:57 UTC
Labels: bug
