### ISSUE TITLE
Encountered error upon loading game

### ISSUE THREAD

**Issue by bloodconfetti** [enemeez/simplefarming#7] opened 2019-08-12 15:50 UTC
[latest.log](https://github.com/enemeez/simplefarming/files/3493327/latest.log)

**Comment by ProsperCraft** [comment] 2019-08-13 12:02
Same, although it was working fine before adding other mods, I may have let a non Forge .45 mod slip in, but it started ok in single player.  Mods not updated to .45 break other mods.

Latest Log-
https://gist.github.com/ProsperCraft/5bc7beaed280cb59110652278c1d2914

Debug log-
https://gist.github.com/ProsperCraft/c13ab5b2de2445cb0f94a166ac622648

Crash report-
https://gist.github.com/ProsperCraft/5202422125a45efbc0affc7e108dbafe

simplefarming-1.14.4-1.0.8
forge-1.14.4-28.0.45

**Comment by ProsperCraft** [comment] 2019-08-13 12:17
https://github.com/Cryptic-Mushroom/The-Midnight/issues/270

This issue with Midnight caused the above crash with Simple Farming.  Once I disabled Simple Farming, the Midnight issue showed itself, and once I removed The Midnight and re-enabled Simple farming it worked fine.

**Comment by bloodconfetti** [comment] 2019-08-13 12:32
Midnight wasn't the cause of my issue, however, just to clarify @enemeez :]

**Comment by enemeez** [comment] 2019-08-13 12:56
Try downgrading to version 1.0.7 temporarily

**Comment by ProsperCraft** [comment] 2019-08-13 13:13
Right, but other mods break Simplefarming, I can tell you with full confidence that simple farming is not the issue, we have been using it with no problems at all with 140 mods.

The only way to find out which mod is causing the issue is to remove mods till you find the problem child leaving simple farming in.

If you want a list of known good working mods check out my pack, we are up to 145 now including simple farming.

https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

Just remove what you don't want and you will be good.

**Comment by TheSnowyChickens** [comment] 2019-09-09 03:00
Same error here :)
But this "bug/crash" is only sometimes during loading.

![grafik](https://user-images.githubusercontent.com/29357962/64500734-b1326580-d2be-11e9-954a-9e71441f4a0f.png)

**Comment by enemeez** [comment] 2019-09-09 03:11
Would you mind providing a log file?

**Comment by TheSnowyChickens** [comment] 2019-09-09 14:40
Yes, but actually no. xd

If I **try** to recreate it, it simply not happen.
#demonstration effect 

In this logs.zip are 7 logs, all the logs, that are in the logs folder.

**Comment by enemeez** [comment] 2019-09-10 20:53
I think I've found the source of error. It's caused by an unused crop that I never finished. I'll have this fixed in a little hotfix update shortly.

**Closed by enemeez** 2019-09-10 20:53 UTC
